clean:
	./gradlew clean

build:
	./gradlew build

test:
	./gradlew test

report:
	./gradlew jacocoTestReport

sonar:
	./gradlew sonar

lint:
	./gradlew checkstyleMain

run:
	./gradlew run

.PHONY: build
